post install LED tests

diff --git a/+POST_INSTALL b/+POST_INSTALL
--- a/+POST_INSTALL
+++ b/+POST_INSTALL
@@ -6,6 +6,21 @@ chmod +x /usr/local/opnsense/scripts/apuled/apuledctl
 /usr/local/etc/rc.configure_plugins
 service configd restart
 
+#LEDs
+LED1="/dev/led/led1"
+LED2="/dev/led/led2"
+LED3="/dev/led/led3"
+LEDKO="/boot/kernel/apuled.ko"
+
+# check if the module file exists
+if [ -e /boot/kernel/apuled.ko ];then
+# Load module
+    kldload $LEDKO 2>&1
+else
+    echo "Error: APU LED module is missing"
+    exit 1
+fi
+
 # starting boot LED message
 # make the initial test
 echo "m-" > $LED1
